Inclusivity changes for CloudStack - rename some offensive words/terms as appropriate, that are meaningful and inclusive.
apache/cloudstack-kubernetes-provider pull request #29
Opened 2021-04-26 07:55 UTC by sureshanaparti

Inclusivity changes for CloudStack - rename some offensive words/terms as appropriate, that are meaningful and inclusive.

- Renamed default git branch name from 'master' to 'main'.

- Replaced whitelist and blacklist with allowlist and denylist respectively.

2021-04-28 05:21 UTC, davidjumani commented on README.md
> +./cloudstack-ccm --cloud-provider external-cloudstack --cloud-config ~/.cloud-config --main k8s-apiserver
This requires changes from the Kubernetes control manager
Ref: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

2021-04-28 05:26 UTC, davidjumani commented on Makefile
> +GIT_VERSION?=$(patsubst v%,%,${GIT_TAG})-main+${GIT_COMMIT}
Might require changes from k8s.io/kubernetes

2021-04-29 06:33 UTC, davidjumani commented on .travis.yml
> +- main
Requires changes in travis 

```
gimme: version specifier 'main' unknown

error: GIMME_GO_VERSION not recognized as valid

  got: main

Failed to run gimme
```

2021-04-29 14:10 UTC, sureshanaparti commented on README.md
> +./cloudstack-ccm --cloud-provider external-cloudstack --cloud-config ~/.cloud-config --main k8s-apiserver
third party changes, i'll revert @davidjumani

2021-05-04 17:55 UTC, rhtyd commented on cloudstack_loadbalancer.go
> +	//allowlist = service.Spec.LoadBalancerSourceRanges
why keep commented code, should we remove this @davidjumani @sureshanaparti ?

2021-05-04 17:55 UTC, rhtyd commented on Makefile
> +GIT_VERSION?=$(patsubst v%,%,${GIT_TAG})-main+${GIT_COMMIT}
@davidjumani can you check again cc @sureshanaparti ?

2021-05-10 08:34 UTC, davidjumani commented on cloudstack_loadbalancer.go
> +	//allowlist = service.Spec.LoadBalancerSourceRanges
I'm for removing it @onitake @joschi36

2021-05-11 07:05 UTC, DaanHoogland requested changes
I think we should leave this PR at only deleting the second bit and not touching the first one.

2021-05-11 07:05 UTC, DaanHoogland commented on Makefile
> +GIT_VERSION?=$(patsubst v%,%,${GIT_TAG})-main+${GIT_COMMIT}
@sureshanaparti @rhtyd , I'm pretty sure `k8s.io/kubernetes/pkg/version.gitVersion=${GIT_VERSION}` falls under the definition of 'not under our control'.

2021-05-19 14:08 UTC, onitake commented on cloudstack_loadbalancer.go
> +	//allowlist = service.Spec.LoadBalancerSourceRanges
Hmmm I don't remember what this was for...
Is it relevant for the needed 1.20 compatibility changes? If no, let's drop it.

2021-05-19 14:11 UTC, onitake commented on Makefile
> +GIT_VERSION?=$(patsubst v%,%,${GIT_TAG})-main+${GIT_COMMIT}
k8s.io/kubernetes/pkg/version.gitVersion is an internal variable in the k8s framework that will be used to print the product version, if you use the option parsing functionality in the framework. Since our product is cloudstack-kubernetes-provider and not Kubernetes, we can put whatever we want in there. Approval from my side.

2021-05-19 14:13 UTC, onitake approved these changes
All changes look good to me.

2021-05-21 08:07 UTC, davidjumani approved these changes

2021-05-21 09:22 UTC, merged